### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by joseRamon13** [Gerpea/rtcp-stream-app#1]
I would like to use this repository on an open source project and since there is no LICENSE file, I'm not sure if I am allowed to use it. 
Would you please upload the applicable license? @Gerpea

**Comment by Gerpea** [comment]
@joseRamon13. Hello, sorry for the late reply. Thank you for asking. And feel free to use this source as you wish.
Added the LICENSE file in this comment 42c5e27
